[package]
name = "RustPacker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
path-absolutize = "3"
fs_extra = "1"
path-clean = "1"
rand = "0.9"
libaes = "0.7"
